/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ryan.commons.packet;

import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.*;

/**
 * 报警信息
 */
public class AlarmPacket implements org.apache.thrift.TBase<AlarmPacket, AlarmPacket._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AlarmPacket");

  private static final org.apache.thrift.protocol.TField ALARMID_FIELD_DESC = new org.apache.thrift.protocol.TField("alarmid", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField IP_FIELD_DESC = new org.apache.thrift.protocol.TField("ip", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TAGID_FIELD_DESC = new org.apache.thrift.protocol.TField("tagid", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("level", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("time", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("result", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField PROP_FIELD_DESC = new org.apache.thrift.protocol.TField("prop", org.apache.thrift.protocol.TType.MAP, (short)8);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AlarmPacketStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AlarmPacketTupleSchemeFactory());
  }

  /**
   * 报警编号
   */
  public int alarmid; // optional
  /**
   * 结点测点所在的报警源ip地址
   */
  public String ip; // optional
  /**
   * 结点测点编号
   */
  public int tagid; // optional
  /**
   * 报警类型
   */
  public int type; // optional
  /**
   * 报警优先级
   */
  public int level; // optional
  /**
   * 报警发生时间
   */
  public long time; // optional
  /**
   * 报警不处理或处理不当的后果
   */
  public String result; // optional
  /**
   * 报警属性，类型不同，属性的数量也不同
   */
  public Map<String,String> prop; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 报警编号
     */
    ALARMID((short)1, "alarmid"),
    /**
     * 结点测点所在的报警源ip地址
     */
    IP((short)2, "ip"),
    /**
     * 结点测点编号
     */
    TAGID((short)3, "tagid"),
    /**
     * 报警类型
     */
    TYPE((short)4, "type"),
    /**
     * 报警优先级
     */
    LEVEL((short)5, "level"),
    /**
     * 报警发生时间
     */
    TIME((short)6, "time"),
    /**
     * 报警不处理或处理不当的后果
     */
    RESULT((short)7, "result"),
    /**
     * 报警属性，类型不同，属性的数量也不同
     */
    PROP((short)8, "prop");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ALARMID
          return ALARMID;
        case 2: // IP
          return IP;
        case 3: // TAGID
          return TAGID;
        case 4: // TYPE
          return TYPE;
        case 5: // LEVEL
          return LEVEL;
        case 6: // TIME
          return TIME;
        case 7: // RESULT
          return RESULT;
        case 8: // PROP
          return PROP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ALARMID_ISSET_ID = 0;
  private static final int __TAGID_ISSET_ID = 1;
  private static final int __TYPE_ISSET_ID = 2;
  private static final int __LEVEL_ISSET_ID = 3;
  private static final int __TIME_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.ALARMID, _Fields.IP, _Fields.TAGID, _Fields.TYPE, _Fields.LEVEL, _Fields.TIME, _Fields.RESULT, _Fields.PROP};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ALARMID, new org.apache.thrift.meta_data.FieldMetaData("alarmid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IP, new org.apache.thrift.meta_data.FieldMetaData("ip", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TAGID, new org.apache.thrift.meta_data.FieldMetaData("tagid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LEVEL, new org.apache.thrift.meta_data.FieldMetaData("level", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TIME, new org.apache.thrift.meta_data.FieldMetaData("time", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.RESULT, new org.apache.thrift.meta_data.FieldMetaData("result", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROP, new org.apache.thrift.meta_data.FieldMetaData("prop", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AlarmPacket.class, metaDataMap);
  }

  public AlarmPacket() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AlarmPacket(AlarmPacket other) {
    __isset_bitfield = other.__isset_bitfield;
    this.alarmid = other.alarmid;
    if (other.isSetIp()) {
      this.ip = other.ip;
    }
    this.tagid = other.tagid;
    this.type = other.type;
    this.level = other.level;
    this.time = other.time;
    if (other.isSetResult()) {
      this.result = other.result;
    }
    if (other.isSetProp()) {
      Map<String,String> __this__prop = new HashMap<String,String>();
      for (Map.Entry<String, String> other_element : other.prop.entrySet()) {

        String other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        String __this__prop_copy_key = other_element_key;

        String __this__prop_copy_value = other_element_value;

        __this__prop.put(__this__prop_copy_key, __this__prop_copy_value);
      }
      this.prop = __this__prop;
    }
  }

  public AlarmPacket deepCopy() {
    return new AlarmPacket(this);
  }

  @Override
  public void clear() {
    setAlarmidIsSet(false);
    this.alarmid = 0;
    this.ip = null;
    setTagidIsSet(false);
    this.tagid = 0;
    setTypeIsSet(false);
    this.type = 0;
    setLevelIsSet(false);
    this.level = 0;
    setTimeIsSet(false);
    this.time = 0;
    this.result = null;
    this.prop = null;
  }

  /**
   * 报警编号
   */
  public int getAlarmid() {
    return this.alarmid;
  }

  /**
   * 报警编号
   */
  public AlarmPacket setAlarmid(int alarmid) {
    this.alarmid = alarmid;
    setAlarmidIsSet(true);
    return this;
  }

  public void unsetAlarmid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ALARMID_ISSET_ID);
  }

  /** Returns true if field alarmid is set (has been assigned a value) and false otherwise */
  public boolean isSetAlarmid() {
    return EncodingUtils.testBit(__isset_bitfield, __ALARMID_ISSET_ID);
  }

  public void setAlarmidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ALARMID_ISSET_ID, value);
  }

  /**
   * 结点测点所在的报警源ip地址
   */
  public String getIp() {
    return this.ip;
  }

  /**
   * 结点测点所在的报警源ip地址
   */
  public AlarmPacket setIp(String ip) {
    this.ip = ip;
    return this;
  }

  public void unsetIp() {
    this.ip = null;
  }

  /** Returns true if field ip is set (has been assigned a value) and false otherwise */
  public boolean isSetIp() {
    return this.ip != null;
  }

  public void setIpIsSet(boolean value) {
    if (!value) {
      this.ip = null;
    }
  }

  /**
   * 结点测点编号
   */
  public int getTagid() {
    return this.tagid;
  }

  /**
   * 结点测点编号
   */
  public AlarmPacket setTagid(int tagid) {
    this.tagid = tagid;
    setTagidIsSet(true);
    return this;
  }

  public void unsetTagid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TAGID_ISSET_ID);
  }

  /** Returns true if field tagid is set (has been assigned a value) and false otherwise */
  public boolean isSetTagid() {
    return EncodingUtils.testBit(__isset_bitfield, __TAGID_ISSET_ID);
  }

  public void setTagidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TAGID_ISSET_ID, value);
  }

  /**
   * 报警类型
   */
  public int getType() {
    return this.type;
  }

  /**
   * 报警类型
   */
  public AlarmPacket setType(int type) {
    this.type = type;
    setTypeIsSet(true);
    return this;
  }

  public void unsetType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return EncodingUtils.testBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  public void setTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TYPE_ISSET_ID, value);
  }

  /**
   * 报警优先级
   */
  public int getLevel() {
    return this.level;
  }

  /**
   * 报警优先级
   */
  public AlarmPacket setLevel(int level) {
    this.level = level;
    setLevelIsSet(true);
    return this;
  }

  public void unsetLevel() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LEVEL_ISSET_ID);
  }

  /** Returns true if field level is set (has been assigned a value) and false otherwise */
  public boolean isSetLevel() {
    return EncodingUtils.testBit(__isset_bitfield, __LEVEL_ISSET_ID);
  }

  public void setLevelIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LEVEL_ISSET_ID, value);
  }

  /**
   * 报警发生时间
   */
  public long getTime() {
    return this.time;
  }

  /**
   * 报警发生时间
   */
  public AlarmPacket setTime(long time) {
    this.time = time;
    setTimeIsSet(true);
    return this;
  }

  public void unsetTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  /** Returns true if field time is set (has been assigned a value) and false otherwise */
  public boolean isSetTime() {
    return EncodingUtils.testBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  public void setTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIME_ISSET_ID, value);
  }

  /**
   * 报警不处理或处理不当的后果
   */
  public String getResult() {
    return this.result;
  }

  /**
   * 报警不处理或处理不当的后果
   */
  public AlarmPacket setResult(String result) {
    this.result = result;
    return this;
  }

  public void unsetResult() {
    this.result = null;
  }

  /** Returns true if field result is set (has been assigned a value) and false otherwise */
  public boolean isSetResult() {
    return this.result != null;
  }

  public void setResultIsSet(boolean value) {
    if (!value) {
      this.result = null;
    }
  }

  public int getPropSize() {
    return (this.prop == null) ? 0 : this.prop.size();
  }

  public void putToProp(String key, String val) {
    if (this.prop == null) {
      this.prop = new HashMap<String,String>();
    }
    this.prop.put(key, val);
  }

  /**
   * 报警属性，类型不同，属性的数量也不同
   */
  public Map<String,String> getProp() {
    return this.prop;
  }

  /**
   * 报警属性，类型不同，属性的数量也不同
   */
  public AlarmPacket setProp(Map<String,String> prop) {
    this.prop = prop;
    return this;
  }

  public void unsetProp() {
    this.prop = null;
  }

  /** Returns true if field prop is set (has been assigned a value) and false otherwise */
  public boolean isSetProp() {
    return this.prop != null;
  }

  public void setPropIsSet(boolean value) {
    if (!value) {
      this.prop = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ALARMID:
      if (value == null) {
        unsetAlarmid();
      } else {
        setAlarmid((Integer)value);
      }
      break;

    case IP:
      if (value == null) {
        unsetIp();
      } else {
        setIp((String)value);
      }
      break;

    case TAGID:
      if (value == null) {
        unsetTagid();
      } else {
        setTagid((Integer)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((Integer)value);
      }
      break;

    case LEVEL:
      if (value == null) {
        unsetLevel();
      } else {
        setLevel((Integer)value);
      }
      break;

    case TIME:
      if (value == null) {
        unsetTime();
      } else {
        setTime((Long)value);
      }
      break;

    case RESULT:
      if (value == null) {
        unsetResult();
      } else {
        setResult((String)value);
      }
      break;

    case PROP:
      if (value == null) {
        unsetProp();
      } else {
        setProp((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ALARMID:
      return Integer.valueOf(getAlarmid());

    case IP:
      return getIp();

    case TAGID:
      return Integer.valueOf(getTagid());

    case TYPE:
      return Integer.valueOf(getType());

    case LEVEL:
      return Integer.valueOf(getLevel());

    case TIME:
      return Long.valueOf(getTime());

    case RESULT:
      return getResult();

    case PROP:
      return getProp();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ALARMID:
      return isSetAlarmid();
    case IP:
      return isSetIp();
    case TAGID:
      return isSetTagid();
    case TYPE:
      return isSetType();
    case LEVEL:
      return isSetLevel();
    case TIME:
      return isSetTime();
    case RESULT:
      return isSetResult();
    case PROP:
      return isSetProp();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AlarmPacket)
      return this.equals((AlarmPacket)that);
    return false;
  }

  public boolean equals(AlarmPacket that) {
    if (that == null)
      return false;

    boolean this_present_alarmid = true && this.isSetAlarmid();
    boolean that_present_alarmid = true && that.isSetAlarmid();
    if (this_present_alarmid || that_present_alarmid) {
      if (!(this_present_alarmid && that_present_alarmid))
        return false;
      if (this.alarmid != that.alarmid)
        return false;
    }

    boolean this_present_ip = true && this.isSetIp();
    boolean that_present_ip = true && that.isSetIp();
    if (this_present_ip || that_present_ip) {
      if (!(this_present_ip && that_present_ip))
        return false;
      if (!this.ip.equals(that.ip))
        return false;
    }

    boolean this_present_tagid = true && this.isSetTagid();
    boolean that_present_tagid = true && that.isSetTagid();
    if (this_present_tagid || that_present_tagid) {
      if (!(this_present_tagid && that_present_tagid))
        return false;
      if (this.tagid != that.tagid)
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (this.type != that.type)
        return false;
    }

    boolean this_present_level = true && this.isSetLevel();
    boolean that_present_level = true && that.isSetLevel();
    if (this_present_level || that_present_level) {
      if (!(this_present_level && that_present_level))
        return false;
      if (this.level != that.level)
        return false;
    }

    boolean this_present_time = true && this.isSetTime();
    boolean that_present_time = true && that.isSetTime();
    if (this_present_time || that_present_time) {
      if (!(this_present_time && that_present_time))
        return false;
      if (this.time != that.time)
        return false;
    }

    boolean this_present_result = true && this.isSetResult();
    boolean that_present_result = true && that.isSetResult();
    if (this_present_result || that_present_result) {
      if (!(this_present_result && that_present_result))
        return false;
      if (!this.result.equals(that.result))
        return false;
    }

    boolean this_present_prop = true && this.isSetProp();
    boolean that_present_prop = true && that.isSetProp();
    if (this_present_prop || that_present_prop) {
      if (!(this_present_prop && that_present_prop))
        return false;
      if (!this.prop.equals(that.prop))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AlarmPacket other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AlarmPacket typedOther = (AlarmPacket)other;

    lastComparison = Boolean.valueOf(isSetAlarmid()).compareTo(typedOther.isSetAlarmid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAlarmid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alarmid, typedOther.alarmid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIp()).compareTo(typedOther.isSetIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ip, typedOther.ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTagid()).compareTo(typedOther.isSetTagid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTagid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tagid, typedOther.tagid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(typedOther.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, typedOther.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLevel()).compareTo(typedOther.isSetLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.level, typedOther.level);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTime()).compareTo(typedOther.isSetTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.time, typedOther.time);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResult()).compareTo(typedOther.isSetResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result, typedOther.result);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProp()).compareTo(typedOther.isSetProp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.prop, typedOther.prop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AlarmPacket(");
    boolean first = true;

    if (isSetAlarmid()) {
      sb.append("alarmid:");
      sb.append(this.alarmid);
      first = false;
    }
    if (isSetIp()) {
      if (!first) sb.append(", ");
      sb.append("ip:");
      if (this.ip == null) {
        sb.append("null");
      } else {
        sb.append(this.ip);
      }
      first = false;
    }
    if (isSetTagid()) {
      if (!first) sb.append(", ");
      sb.append("tagid:");
      sb.append(this.tagid);
      first = false;
    }
    if (isSetType()) {
      if (!first) sb.append(", ");
      sb.append("type:");
      sb.append(this.type);
      first = false;
    }
    if (isSetLevel()) {
      if (!first) sb.append(", ");
      sb.append("level:");
      sb.append(this.level);
      first = false;
    }
    if (isSetTime()) {
      if (!first) sb.append(", ");
      sb.append("time:");
      sb.append(this.time);
      first = false;
    }
    if (isSetResult()) {
      if (!first) sb.append(", ");
      sb.append("result:");
      if (this.result == null) {
        sb.append("null");
      } else {
        sb.append(this.result);
      }
      first = false;
    }
    if (isSetProp()) {
      if (!first) sb.append(", ");
      sb.append("prop:");
      if (this.prop == null) {
        sb.append("null");
      } else {
        sb.append(this.prop);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AlarmPacketStandardSchemeFactory implements SchemeFactory {
    public AlarmPacketStandardScheme getScheme() {
      return new AlarmPacketStandardScheme();
    }
  }

  private static class AlarmPacketStandardScheme extends StandardScheme<AlarmPacket> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AlarmPacket struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // ALARMID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.alarmid = iprot.readI32();
              struct.setAlarmidIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ip = iprot.readString();
              struct.setIpIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TAGID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tagid = iprot.readI32();
              struct.setTagidIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = iprot.readI32();
              struct.setTypeIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.level = iprot.readI32();
              struct.setLevelIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.time = iprot.readI64();
              struct.setTimeIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.result = iprot.readString();
              struct.setResultIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PROP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map26 = iprot.readMapBegin();
                struct.prop = new HashMap<String,String>(2*_map26.size);
                for (int _i27 = 0; _i27 < _map26.size; ++_i27)
                {
                  String _key28; // required
                  String _val29; // required
                  _key28 = iprot.readString();
                  _val29 = iprot.readString();
                  struct.prop.put(_key28, _val29);
                }
                iprot.readMapEnd();
              }
              struct.setPropIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AlarmPacket struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetAlarmid()) {
        oprot.writeFieldBegin(ALARMID_FIELD_DESC);
        oprot.writeI32(struct.alarmid);
        oprot.writeFieldEnd();
      }
      if (struct.ip != null) {
        if (struct.isSetIp()) {
          oprot.writeFieldBegin(IP_FIELD_DESC);
          oprot.writeString(struct.ip);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetTagid()) {
        oprot.writeFieldBegin(TAGID_FIELD_DESC);
        oprot.writeI32(struct.tagid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetType()) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLevel()) {
        oprot.writeFieldBegin(LEVEL_FIELD_DESC);
        oprot.writeI32(struct.level);
        oprot.writeFieldEnd();
      }
      if (struct.isSetTime()) {
        oprot.writeFieldBegin(TIME_FIELD_DESC);
        oprot.writeI64(struct.time);
        oprot.writeFieldEnd();
      }
      if (struct.result != null) {
        if (struct.isSetResult()) {
          oprot.writeFieldBegin(RESULT_FIELD_DESC);
          oprot.writeString(struct.result);
          oprot.writeFieldEnd();
        }
      }
      if (struct.prop != null) {
        if (struct.isSetProp()) {
          oprot.writeFieldBegin(PROP_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.prop.size()));
            for (Map.Entry<String, String> _iter30 : struct.prop.entrySet())
            {
              oprot.writeString(_iter30.getKey());
              oprot.writeString(_iter30.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AlarmPacketTupleSchemeFactory implements SchemeFactory {
    public AlarmPacketTupleScheme getScheme() {
      return new AlarmPacketTupleScheme();
    }
  }

  private static class AlarmPacketTupleScheme extends TupleScheme<AlarmPacket> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AlarmPacket struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAlarmid()) {
        optionals.set(0);
      }
      if (struct.isSetIp()) {
        optionals.set(1);
      }
      if (struct.isSetTagid()) {
        optionals.set(2);
      }
      if (struct.isSetType()) {
        optionals.set(3);
      }
      if (struct.isSetLevel()) {
        optionals.set(4);
      }
      if (struct.isSetTime()) {
        optionals.set(5);
      }
      if (struct.isSetResult()) {
        optionals.set(6);
      }
      if (struct.isSetProp()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetAlarmid()) {
        oprot.writeI32(struct.alarmid);
      }
      if (struct.isSetIp()) {
        oprot.writeString(struct.ip);
      }
      if (struct.isSetTagid()) {
        oprot.writeI32(struct.tagid);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type);
      }
      if (struct.isSetLevel()) {
        oprot.writeI32(struct.level);
      }
      if (struct.isSetTime()) {
        oprot.writeI64(struct.time);
      }
      if (struct.isSetResult()) {
        oprot.writeString(struct.result);
      }
      if (struct.isSetProp()) {
        {
          oprot.writeI32(struct.prop.size());
          for (Map.Entry<String, String> _iter31 : struct.prop.entrySet())
          {
            oprot.writeString(_iter31.getKey());
            oprot.writeString(_iter31.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AlarmPacket struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.alarmid = iprot.readI32();
        struct.setAlarmidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ip = iprot.readString();
        struct.setIpIsSet(true);
      }
      if (incoming.get(2)) {
        struct.tagid = iprot.readI32();
        struct.setTagidIsSet(true);
      }
      if (incoming.get(3)) {
        struct.type = iprot.readI32();
        struct.setTypeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.level = iprot.readI32();
        struct.setLevelIsSet(true);
      }
      if (incoming.get(5)) {
        struct.time = iprot.readI64();
        struct.setTimeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.result = iprot.readString();
        struct.setResultIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TMap _map32 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.prop = new HashMap<String,String>(2*_map32.size);
          for (int _i33 = 0; _i33 < _map32.size; ++_i33)
          {
            String _key34; // required
            String _val35; // required
            _key34 = iprot.readString();
            _val35 = iprot.readString();
            struct.prop.put(_key34, _val35);
          }
        }
        struct.setPropIsSet(true);
      }
    }
  }

}

