/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ryan.commons.packet;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.*;

/**
 * 报警列表信息
 */
public class AlarmArrayPacket implements org.apache.thrift.TBase<AlarmArrayPacket, AlarmArrayPacket._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AlarmArrayPacket");

  private static final org.apache.thrift.protocol.TField ALARM_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("alarmList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AlarmArrayPacketStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AlarmArrayPacketTupleSchemeFactory());
  }

  /**
   * 报警列表，批量发送时使用
   */
  public List<AlarmPacket> alarmList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 报警列表，批量发送时使用
     */
    ALARM_LIST((short)1, "alarmList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ALARM_LIST
          return ALARM_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.ALARM_LIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ALARM_LIST, new org.apache.thrift.meta_data.FieldMetaData("alarmList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AlarmPacket.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AlarmArrayPacket.class, metaDataMap);
  }

  public AlarmArrayPacket() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AlarmArrayPacket(AlarmArrayPacket other) {
    if (other.isSetAlarmList()) {
      List<AlarmPacket> __this__alarmList = new ArrayList<AlarmPacket>();
      for (AlarmPacket other_element : other.alarmList) {
        __this__alarmList.add(new AlarmPacket(other_element));
      }
      this.alarmList = __this__alarmList;
    }
  }

  public AlarmArrayPacket deepCopy() {
    return new AlarmArrayPacket(this);
  }

  @Override
  public void clear() {
    this.alarmList = null;
  }

  public int getAlarmListSize() {
    return (this.alarmList == null) ? 0 : this.alarmList.size();
  }

  public java.util.Iterator<AlarmPacket> getAlarmListIterator() {
    return (this.alarmList == null) ? null : this.alarmList.iterator();
  }

  public void addToAlarmList(AlarmPacket elem) {
    if (this.alarmList == null) {
      this.alarmList = new ArrayList<AlarmPacket>();
    }
    this.alarmList.add(elem);
  }

  /**
   * 报警列表，批量发送时使用
   */
  public List<AlarmPacket> getAlarmList() {
    return this.alarmList;
  }

  /**
   * 报警列表，批量发送时使用
   */
  public AlarmArrayPacket setAlarmList(List<AlarmPacket> alarmList) {
    this.alarmList = alarmList;
    return this;
  }

  public void unsetAlarmList() {
    this.alarmList = null;
  }

  /** Returns true if field alarmList is set (has been assigned a value) and false otherwise */
  public boolean isSetAlarmList() {
    return this.alarmList != null;
  }

  public void setAlarmListIsSet(boolean value) {
    if (!value) {
      this.alarmList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ALARM_LIST:
      if (value == null) {
        unsetAlarmList();
      } else {
        setAlarmList((List<AlarmPacket>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ALARM_LIST:
      return getAlarmList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ALARM_LIST:
      return isSetAlarmList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AlarmArrayPacket)
      return this.equals((AlarmArrayPacket)that);
    return false;
  }

  public boolean equals(AlarmArrayPacket that) {
    if (that == null)
      return false;

    boolean this_present_alarmList = true && this.isSetAlarmList();
    boolean that_present_alarmList = true && that.isSetAlarmList();
    if (this_present_alarmList || that_present_alarmList) {
      if (!(this_present_alarmList && that_present_alarmList))
        return false;
      if (!this.alarmList.equals(that.alarmList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AlarmArrayPacket other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AlarmArrayPacket typedOther = (AlarmArrayPacket)other;

    lastComparison = Boolean.valueOf(isSetAlarmList()).compareTo(typedOther.isSetAlarmList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAlarmList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alarmList, typedOther.alarmList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AlarmArrayPacket(");
    boolean first = true;

    if (isSetAlarmList()) {
      sb.append("alarmList:");
      if (this.alarmList == null) {
        sb.append("null");
      } else {
        sb.append(this.alarmList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AlarmArrayPacketStandardSchemeFactory implements SchemeFactory {
    public AlarmArrayPacketStandardScheme getScheme() {
      return new AlarmArrayPacketStandardScheme();
    }
  }

  private static class AlarmArrayPacketStandardScheme extends StandardScheme<AlarmArrayPacket> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AlarmArrayPacket struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // ALARM_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list36 = iprot.readListBegin();
                struct.alarmList = new ArrayList<AlarmPacket>(_list36.size);
                for (int _i37 = 0; _i37 < _list36.size; ++_i37)
                {
                  AlarmPacket _elem38; // required
                  _elem38 = new AlarmPacket();
                  _elem38.read(iprot);
                  struct.alarmList.add(_elem38);
                }
                iprot.readListEnd();
              }
              struct.setAlarmListIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AlarmArrayPacket struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.alarmList != null) {
        if (struct.isSetAlarmList()) {
          oprot.writeFieldBegin(ALARM_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.alarmList.size()));
            for (AlarmPacket _iter39 : struct.alarmList)
            {
              _iter39.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AlarmArrayPacketTupleSchemeFactory implements SchemeFactory {
    public AlarmArrayPacketTupleScheme getScheme() {
      return new AlarmArrayPacketTupleScheme();
    }
  }

  private static class AlarmArrayPacketTupleScheme extends TupleScheme<AlarmArrayPacket> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AlarmArrayPacket struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAlarmList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAlarmList()) {
        {
          oprot.writeI32(struct.alarmList.size());
          for (AlarmPacket _iter40 : struct.alarmList)
          {
            _iter40.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AlarmArrayPacket struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list41 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.alarmList = new ArrayList<AlarmPacket>(_list41.size);
          for (int _i42 = 0; _i42 < _list41.size; ++_i42)
          {
            AlarmPacket _elem43; // required
            _elem43 = new AlarmPacket();
            _elem43.read(iprot);
            struct.alarmList.add(_elem43);
          }
        }
        struct.setAlarmListIsSet(true);
      }
    }
  }

}

