/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ryan.commons.packet;

import java.util.HashMap;
import java.util.Map;

public class MessagePacketProtocalConstants {

  /**
   * 报警源信息 *
   */
  public static final byte ALARM_SOURCE_COMMAND = (byte)0;

  /**
   * 结点测点信息  *
   */
  public static final byte NODE_COMMAND = (byte)1;

  /**
   * 结点测点列表信息 *
   */
  public static final byte NODE_LIST_COMMAND = (byte)2;

  /**
   * 报警信息 *
   */
  public static final byte ALARM_COMMAND = (byte)3;

  /**
   * 报警列表信息 *
   */
  public static final byte ALARM_LIST_COMMAND = (byte)4;

  /**
   * 报警维护信息  *
   */
  public static final byte MAINTAIN_COMMAND = (byte)5;

  /**
   * 命令字和消息类映射关系定义
   */
  public static final Map<Byte,String> CMD_PACKET_DICT = new HashMap<Byte,String>();
  static {
    CMD_PACKET_DICT.put((byte)0, "AlarmSourcePacket");
    CMD_PACKET_DICT.put((byte)1, "NodePacket");
    CMD_PACKET_DICT.put((byte)2, "NodeArrayPacket");
    CMD_PACKET_DICT.put((byte)3, "AlarmPacket");
    CMD_PACKET_DICT.put((byte)4, "AlarmArrayPacket");
    CMD_PACKET_DICT.put((byte)5, "AlarmMaintainPacket");
  }

  /**
   * 包版本号 *
   */
  public static final int PACKET_VERSION = 1;

  /**
   * 测点的当前值
   */
  public static final String PV = "pv";

  /**
   * 测点的质量戳
   */
  public static final String QUALITY = "quality";

  /**
   * 测点的时间戳
   */
  public static final String PV_TIME = "pv_time";

  /**
   * 关信息
   */
  public static final String OFF_MSG = "offmessage";

  /**
   * 开信息
   */
  public static final String ON_MSG = "onmessage";

  /**
   * 报警延迟
   */
  public static final String DELAY = "delay";

  /**
   * 报警恢复死区
   */
  public static final String DEAD_ZONE = "dead_zone";

  /**
   * 低低限设定
   */
  public static final String LOW_LOW = "lowlow";

  /**
   * 低限设定
   */
  public static final String LOW = "low";

  /**
   * 高高限设定
   */
  public static final String HIGH_HIGH = "highhigh";

  /**
   * 高限设定
   */
  public static final String HIGH = "high";

  /**
   * 变化率报警限值设定
   */
  public static final String RATE = "rate";

  /**
   * 变化率变化设定
   */
  public static final String RATE_PERIOD = "rateperiod";

  /**
   * 偏差报警目标值
   */
  public static final String DEV_SP = "dev_sp";

  /**
   * 偏差报警偏差值
   */
  public static final String DEV_VALUE = "dev_value";

  /**
   * 测量下限
   */
  public static final String RANGE_MAX = "range_max";

  /**
   * 测量上限
   */
  public static final String RANGE_MIN = "range_min";

  /**
   * 报警子状态
   */
  public static final String SUB_STATUE = "sub_status";

  /**
   * 报警评论
   */
  public static final String COMMET = "commet";

}
